export const UPDATE_CANVAS_DATE = 'UPDATE_CANVAS_DATE'
export const UPDATE_CANVAS_WIDGET_DATA = 'UPDATE_CANVAS_WIDGET_DATA'
export const UPDATE_CANVAS_WIDGET_LIST_DATA = 'UPDATE_CANVAS_WIDGET_LIST_DATA'
