import Vue from 'vue'

// mouseWidget
export const CANVAS_WIDGET_RESIZE = 'CANVAS_WIDGET_RESIZE'
export const CANVAS_HOVER_MENU = 'CANVAS_HOVER_MENU'
export const CANVAS_WIDGET_BOOTSTRAP = 'CANVAS_WIDGET_BOOTSTRAP'
export const CANVAS_WIDGET_MOUSEDOWN = 'CANVAS_WIDGET_MOUSEDOWN'
export const CANVAS_WIDGET_RESIZER_VISIBLE = 'CANVAS_WIDGET_RESIZER_VISIBLE'

// document
export const DOCUMENT_MOUSE_DOWN = 'DOCUMENT_MOUSE_DOWN'
export const DOCUMENT_MOUSE_MOVE = 'DOCUMENT_MOUSE_MOVE'
export const DOCUMENT_MOUSE_UP = 'DOCUMENT_MOUSE_UP'
export const DOCUMENT_CONTEXT_MENU = 'DOCUMENT_CONTEXT_MENU'

// screen
export const SCREEN_SCROLL = 'SCREEN_SCROLL'
export const SCREEN_SCROLL_END = 'SCREEN_SCROLL_END'

export default new Vue()
