export const UPDATE_RULER_DATA = 'UPDATE_RULER_DATA'
export const ADD_REFERENCE_LINE = 'ADD_REFERENCE_LINE'
export const DELETE_REFERENCE_LINE = 'DELETE_REFERENCE_LINE'
export const TOGGLE_REFERENCE_LINE_VISIBLE = 'TOGGLE_REFERENCE_LINE_VISIBLE'
